In [6]:
l = [34, 56, 7, 787]
import numpy as np

In [8]:
np.array(l)

array([ 34,  56,   7, 787])

In [7]:
b = np.array([12, 234, True, 'abc'])

In [9]:
b

array(['12', '234', 'True', 'abc'], dtype='<U21')

In [10]:
a = np.array(l)

In [11]:
a.mean()

221.0

In [12]:
a.max()

787

In [13]:
a.sum()


884

In [14]:
a.max()

787

In [18]:
# slicing arrays
b = a[2:4] 
b

array([  7, 787])

In [19]:
b[0]

7

In [20]:
b[:] = 123

In [21]:
b

array([123, 123])

In [22]:
a

array([ 34,  56, 123, 123])

In [23]:
c = a.copy()

In [24]:
c

array([ 34,  56, 123, 123])

In [25]:
c[2] = 2

In [26]:
c

array([ 34,  56,   2, 123])

In [27]:
a

array([ 34,  56, 123, 123])