In [30]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

Profit for each month

In [52]:
import numpy as np
arr_revenue = np.array(revenue)
arr_expenses = np.array(expenses)
profit = arr_revenue - arr_expenses
print(np.around(profit / 1000, decimals=2))

[ 2.52  1.91 -3.71 -2.91 -0.6   7.27  8.21  3.94  3.33 -2.24  0.66 11.63]


Profit after tax

In [50]:
tax = 0.3
profit_after_tax = profit - (profit * tax)
print(np.around(profit_after_tax / 1000, decimals=2))

[ 1.77  1.34 -2.6  -2.04 -0.42  5.09  5.75  2.76  2.33 -1.57  0.46  8.14]


profit margin for each month

In [54]:
# profit margin for each month
profit_margin = profit_after_tax / arr_revenue
print(np.round(profit_margin * 100, decimals=0))

[ 12.  18. -30. -22.  -5.  63.  50.  28.  23. -11.   4.  53.]


good months - where the profit after tax was greater than the mean for the year

In [53]:
good_months = profit_after_tax > np.mean(profit_after_tax)
print(good_months)

[ True False False False False  True  True  True  True False False  True]


Bad months - profit after tax < mean for the year

In [55]:
bad_months = profit_after_tax < np.mean(profit_after_tax)
print(bad_months)

[False  True  True  True  True False False False False  True  True False]


Best month

In [56]:
best_month = np.max(profit_after_tax)
print(best_month)

8140.678000000001


worst month

In [57]:
worst_month = np.min(profit_after_tax)
print(worst_month)

-2595.4530000000004
